name: Combine PRs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Combine PRs
        uses: github/combine-prs@v5.2.0
        with:
          pr_title: 'Combined PRs'
          pr_body_header: '# Combined PRs'
          labels: combined-pr
